export type Platform = 'leetcode' | 'leetcode-cn';

export type ProblemDifficulty = 'Easy' | 'Medium' | 'Hard' | 'Unknown';

export type ReviewRating = 'too_easy' | 'normal' | 'hard' | 'no_clue';

export type ReviewSource = 'accepted_modal' | 'daily_plan' | 'manual_note' | 'import';

export type Locale = 'en' | 'zh-CN';
export type DebugScenarioPreset = 'empty' | 'mixed' | 'overdue' | 'import_preview';
export type LocalizedText = string | Partial<Record<Locale, string>>;

/**
 * FSRS State Enum (matching ts-fsrs)
 */
export enum FSRSState {
  New = 0,
  Learning = 1,
  Review = 2,
  Relearning = 3
}

export interface Problem {
  id: string;
  platform: Platform;
  titleSlug: string;
  title: string;
  titleZh?: string;
  difficulty: ProblemDifficulty;
  url: string;
  firstAcceptedAt: string;
  lastAcceptedAt: string;
  lastReviewedAt?: string;
  nextReviewAt: string;
  
  // FSRS Fields
  stability: number;
  difficultyScore: number; // Renamed to avoid clash with ProblemDifficulty
  elapsedDays: number;
  scheduledDays: number;
  reps: number;
  lapses: number;
  learning_steps: number;
  state: FSRSState;
  lastReviewAt?: string;

  // Legacy fields (kept for migration/UI fallback)
  reviewStage: number;
  currentIntervalDays: number;
  easeFactor: number;
  
  reviewCount: number;
  overdueCount: number;
  archived: boolean;
  tags?: string[];
  createdAt: string;
  updatedAt: string;
}

export interface ReviewLog {
  id: string;
  problemId: string;
  reviewedAt: string;
  source: ReviewSource;
  rating: ReviewRating;
  
  // FSRS rollback fields. These must represent the card state before this review.
  fsrsDueAt: string;
  stability: number;
  difficultyScore: number;
  elapsedDays: number;
  lastElapsedDays: number;
  scheduledDays: number;
  generatedDueAt: string; // The due date generated by this review
  lapses: number;
  learning_steps: number;
  state: FSRSState;

  // Legacy fields
  previousReviewStage: number;
  nextReviewStage: number;
  previousIntervalDays?: number;
  nextIntervalDays: number;
  previousNextReviewAt?: string;
  nextReviewAt: string;
  createdAt: string;
}

export interface ProblemNote {
  problemId: string;
  markdown: string;
  createdAt: string;
  updatedAt: string;
}

export interface ReviewPolicy {
  baseIntervalsDays: number[];
  ratingAdjustments: {
    too_easy: {
      stageDelta: number;
      intervalMultiplier: number;
    };
    normal: {
      stageDelta: number;
      intervalMultiplier: number;
    };
    hard: {
      stageDelta: number;
      intervalMultiplier: number;
    };
    no_clue: {
      stageDelta: number;
      fixedIntervalDays: number;
    };
  };
}

export interface ReminderSettings {
  enabled: boolean;
  dailyReminderTime: string;
  notifyOverdue: boolean;
  overdueThresholdDays: number;
  weeklyReportExportEnabled: boolean;
}

export type EmailProvider = 'official' | 'emailjs' | 'resend' | 'custom';

export interface EmailWebhookSettings {
  enabled: boolean;
  toEmail?: string;
  betaAccessCode?: string;
  lastError?: string;
  lastSentAt?: string;
}

export interface SupabaseSyncSettings {
  enabled: boolean;
  syncKey?: string;
  lastSyncedAt?: string;
  lastError?: string;
}

export interface ReminderProblemDelivery {
  problemId: string;
  lastSentAt?: string;
  lastSentDate?: string;
  provider?: EmailProvider;
  successCount: number;
  failureCount: number;
  lastErrorAt?: string;
  lastError?: string;
}

export interface ReminderDeliveryState {
  lastDailyNotificationDate?: string;
  lastWeeklySummarySentDate?: string;
  lastWeeklyReportExportedDate?: string;
  emailByProblemId: Record<string, ReminderProblemDelivery>;
}

export interface AnnouncementAction {
  label: LocalizedText;
  url: string;
  download?: boolean;
}

export type AnnouncementSeverity = 'info' | 'success' | 'warning' | 'critical';

export interface ExtensionAnnouncement {
  schemaVersion: 1;
  noticeId: string;
  latestVersion: string;
  minVersion?: string;
  severity: AnnouncementSeverity;
  title: LocalizedText;
  body?: LocalizedText;
  actions: AnnouncementAction[];
}

export interface DailyCompletionMessage {
  title: LocalizedText;
  body: LocalizedText;
}

export interface DailyCompletionMessagesConfig {
  schemaVersion: 1;
  enabled: boolean;
  messages: DailyCompletionMessage[];
}

export interface WeeklyReviewPoint {
  date: string;
  label: string;
  reviewCount: number;
}

export type MasteryTier = 'new' | 'familiar' | 'proficient' | 'mastered';

export interface WeeklyDifficultyCount {
  difficulty: ProblemDifficulty;
  count: number;
}

export interface WeeklyTagCount {
  tag: string;
  count: number;
}

export interface WeeklyProblemSummary {
  id: string;
  title: string;
  titleZh?: string;
  titleSlug: string;
  url: string;
  difficulty: ProblemDifficulty;
  tags?: string[];
  reviewCount: number;
  nextReviewAt: string;
  stability: number;
  daysOverdue: number;
  retrievability: number;
  masteryTier: MasteryTier;
}

export interface WeeklySummaryStats {
  totalProblems: number;
  dueCount: number;
  overdueCount: number;
  reviewedProblemsThisWeekCount: number;
  acceptedProblemsThisWeekCount: number;
  dailyReviewPoints: WeeklyReviewPoint[];
  difficultyBreakdown?: WeeklyDifficultyCount[];
  topTags?: WeeklyTagCount[];
  acceptedProblemCards?: WeeklyProblemSummary[];
  reviewedProblemCards?: WeeklyProblemSummary[];
}

export interface HotQuestionCompany {
  id: number;
  name: string;
  isNew: boolean;
  syncedAt?: string;
}

export type HotQuestionDifficulty = 1 | 2 | 3;

export interface HotQuestion {
  source: 'codetop';
  companyId: number;
  companyName: string;
  leetcodeFrontendId: string;
  leetcodeQuestionId?: number;
  title: string;
  slugTitle: string;
  difficulty: HotQuestionDifficulty;
  frequency: number;
  rank?: number;
  sourceUpdatedAt?: string;
  syncedAt?: string;
}

export type HotQuestionReason =
  | 'company_hot'
  | 'not_solved'
  | 'review_due'
  | 'previously_hard'
  | 'recently_updated';

export interface HotQuestionRecommendation extends HotQuestion {
  score: number;
  reasons: HotQuestionReason[];
  matchedProblemId?: string;
  solved: boolean;
}

export interface HotQuestionCacheState {
  schemaVersion: 1;
  selectedCompanyId?: number;
  companies: HotQuestionCompany[];
  questionsByCompanyId: Record<string, HotQuestion[]>;
  fetchedAtByCompanyId: Record<string, string>;
  syncedAt?: string;
  stale?: boolean;
  lastError?: string;
}

export interface HotQuestionsRuntimeData {
  companies: HotQuestionCompany[];
  selectedCompanyId?: number;
  questions: HotQuestion[];
  recommendations: HotQuestionRecommendation[];
  stale?: boolean;
  syncedAt?: string;
  fetchedAt?: string;
  lastError?: string;
}

export interface ReviewCoachInput {
  periodStart: string;
  periodEnd: string;
  weeklySummary: WeeklySummaryStats;
  dueQuestions: WeeklyProblemSummary[];
  candidateQuestions: HotQuestionRecommendation[];
}

export interface ReviewCoachOutput {
  summary: string;
  weakPoints: string[];
  recommendedQuestions: Array<{
    leetcodeFrontendId: string;
    priority: 'high' | 'medium' | 'low';
    reason: string;
  }>;
  nextPlan: Array<{
    day: number;
    task: string;
    questionIds: string[];
  }>;
  encouragement: string;
}

export interface UserSettings {
  autoShowAcceptedModal: boolean;
  locale: Locale;
  reviewPolicy: ReviewPolicy;
  reminders: ReminderSettings;
  emailWebhook: EmailWebhookSettings;
  cloudSync: SupabaseSyncSettings;
  themeMode: 'system' | 'light' | 'dark';
  dailyReviewLimit: number;
}

export interface ExtensionStorageState {
  version: number;
  problemsById: Record<string, Problem>;
  reviewLogsById: Record<string, ReviewLog>;
  notesByProblemId: Record<string, ProblemNote>;
  settings: UserSettings;
  metadata: {
    debugMode?: boolean;
    debugActivePreset?: DebugScenarioPreset;
    debugCoveredPresets?: DebugScenarioPreset[];
    lastNotificationAt?: string;
    storageBackend: 'local';
    migratedAt?: string;
    reminderDelivery?: ReminderDeliveryState;
    dismissedAnnouncementIds?: string[];
  };
}

export interface ProblemIdentity {
  platform: Platform;
  titleSlug: string;
  title: string;
  titleZh?: string;
  difficulty: ProblemDifficulty;
  tags?: string[];
  url: string;
}

export interface DueProblem extends Problem {
  daysOverdue: number;
  retrievability: number; // 0-1 (e.g. 0.92)
  masteryTier: MasteryTier;
}

export interface ReviewStats {
  totalProblems: number;
  dueCount: number;
  overdueCount: number;
  completedTodayCount: number;
  reviewedLast7DaysCount: number;
}

export interface ImportPreview {
  valid: boolean;
  version?: number;
  problemCount: number;
  noteCount: number;
  reviewLogCount: number;
  newProblemCount: number;
  overwrittenProblemCount: number;
  warningMessages: string[];
  errorMessages: string[];
}

export interface ReviewResult {
  problem: Problem;
  log: ReviewLog;
}

export type RuntimeRequest =
  | {
      type: 'UPSERT_ACCEPTED_REVIEW';
      payload: {
        identity: ProblemIdentity;
        rating: ReviewRating;
        source: ReviewSource;
      };
    }
  | { type: 'GET_DAILY_PLAN' }
  | {
      type: 'GET_HOT_QUESTIONS';
      payload?: {
        force?: boolean;
      };
    }
  | {
      type: 'UPDATE_HOT_QUESTION_COMPANY';
      payload: {
        companyId: number;
      };
    }
  | { type: 'REFRESH_HOT_QUESTIONS' }
  | { type: 'CHECK_ANNOUNCEMENT' }
  | { type: 'GET_DAILY_COMPLETION_MESSAGES' }
  | {
      type: 'DISMISS_ANNOUNCEMENT';
      payload: {
        noticeId: string;
      };
    }
  | {
      type: 'OPEN_ANNOUNCEMENT_ACTION';
      payload: {
        action: AnnouncementAction;
      };
    }
  | {
      type: 'UPDATE_DAILY_REVIEW_LIMIT';
      payload: {
        limit: number;
      };
    }
  | {
      type: 'SAVE_NOTE';
      payload: {
        problemId: string;
        markdown: string;
      };
    }
  | {
      type: 'OPEN_PROBLEM';
      payload: {
        url: string;
      };
    }
  | { type: 'SEND_TEST_EMAIL' }
  | { type: 'EXPORT_WEEKLY_REPORT' }
  | { type: 'SEND_TEST_NOTIFICATION' }
  | { type: 'CHECK_REMINDERS' }
  | {
      type: 'PREVIEW_IMPORT';
      payload: {
        input: unknown;
      };
    }
  | {
      type: 'IMPORT_STATE_CONFIRMED';
      payload: {
        input: unknown;
      };
    }
  | {
      type: 'OPEN_URL';
      payload: {
        url: string;
      };
    }
  | {
      type: 'RESET_TO_TODAY';
      payload: {
        problemId: string;
      };
    }
  | {
      type: 'ARCHIVE_PROBLEM';
      payload: {
        problemId: string;
      };
    };

export interface RuntimeResponse<T = unknown> {
  ok: boolean;
  data?: T;
  error?: string;
}
